datasource:

  primary:
    #driver-class-name: com.mysql.cj.jdbc.Driver #可以不设置driver-class-name，druid会自动探测
    #url: jdbc:mysql://112.74.170.75:3306/spy_schedule_job?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://112.74.170.75:3306/spy_schedule_job?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 

  secondary:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://112.74.170.75:3306/hive?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 


  default: primary
  type: com.alibaba.druid.pool.DruidDataSource
  initialSize: 0
  minIdle: 0
  maxActive: 5
  maxWait: 15000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 1800000
  removeAbandonedTimeoutMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: false
  maxOpenPreparedStatements: 10
  filters: stat,wall,slf4j
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
